### Problem 1

In [ ]:
import numpy as np

def givens_cs(a, b):
    if b == 0.0:
        return 1.0, 0.0
    r = np.hypot(a, b)
    c = a / r
    s = b / r
    return c, s

def qr_rotation(A_init):
    A = A_init.astype(float).copy()
    m, n = A.shape
    Q = np.eye(m)
    for j in range(n):
        for i in range(m-1, j, -1):
            a = A[i-1, j]
            b = A[i, j]
            if abs(b) < 1e-15:
                continue
            c, s = givens_cs(a, b)
            G = np.eye(m)
            G[i-1, i-1] = c
            G[i-1, i]   = s
            G[i,   i-1] = -s
            G[i,   i]   = c
            A = G @ A
            Q = Q @ G.T
    R = A
    return Q, R

A = np.array([
    [8, 5, 1, 0],
    [5, 8, 4, 4],
    [1, 4, 2, 7],
    [0, 4, 7, 4]
], dtype=float)

Q, R = qr_rotation(A)

print("Q:")
print(Q)
print("\nR:")
print(R)
print("\Q R")
print(Q @ R)

Q:
[[ 0.84327404 -0.37792504  0.26595486 -0.27446232]
 [ 0.52704628  0.51070951 -0.3364329   0.59009399]
 [ 0.10540926  0.46985275 -0.44547439 -0.75477139]
 [ 0.          0.61285141  0.78589661 -0.0823387 ]]

R:
[[ 9.48683298e+00  8.85437745e+00  3.16227766e+00  2.84604989e+00]
 [-1.59633686e-16  6.52686755e+00  6.89457840e+00  7.78321295e+00]
 [ 1.12338031e-16  1.80294070e-16  3.53055077e+00 -1.32046588e+00]
 [-1.15931541e-16 -1.86061384e-16 -9.58211740e-17 -3.25237853e+00]]

Check Q^T Q (should be close to I):
[[ 1.00000000e+00  6.68535112e-17 -5.23706133e-17  2.43778993e-17]
 [ 6.68535112e-17  1.00000000e+00 -9.68607307e-17  4.03305323e-17]
 [-5.23706133e-17 -9.68607307e-17  1.00000000e+00  1.12172763e-18]
 [ 2.43778993e-17  4.03305323e-17  1.12172763e-18  1.00000000e+00]]

Check Q R (should be close to A):
[[ 8.00000000e+00  5.00000000e+00  1.00000000e+00 -8.58025927e-16]
 [ 5.00000000e+00  8.00000000e+00  4.00000000e+00  4.00000000e+00]
 [ 1.00000000e+00  4.00000000e+00  2.0000000