# Midterm Exam 4501
Sherlock

### Problem 2:

In [41]:
import numpy as np
import matplotlib.pyplot as plt

# building the matix
def build_A(m = 98, n = 5):
    i = np.arange(1, m + 1)[:, None]
    j = np.arange(1, n + 1)[None, :]
    A = np.sin(np.pi * (i - 0.5) * j / m)
    return A.astype(float)

# QR factorization
def qr_factorization(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j].copy() # getting columns of A as v
        
        # removing the components of previous directions
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], v)
            v -= R[i, j] * Q[:, i]
            
        # normalize
        R[j, j] = np.linalg.norm(v, 2)
    return Q, R

m, n = 98, 5
A = build_A(m, n)
Q, R = qr_factorization(A)

# print out results
np.set_printoptions(formatter={'float': '{:0.5f}'.format})
print("R =\n", R)

R =
 [[7.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 7.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 7.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 7.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 7.00000]]


### Problem 3(b):

In [42]:
lam = 2.5 # lambda inside (a)'s calcuated range

def f(x):
    return np.pi - 20.0 * np.arctan(1.0 / x) - 8.0 * np.arctan(3.0 / 79.0)

def relax(x0, lam, max_iter_num = 6):
    res = []
    x = x0
    for k in range(max_iter_num):
        x = x - lam * f(x)
        res.append(x)
    return res

x0 = 9.0
res = relax(x0, lam)

print("Relaxation method:")
for k, x in enumerate(res, start = 1):
    print(f"x{k} = {x:.5f}")

Relaxation method:
x1 = 7.43801
x2 = 7.02532
x3 = 7.00009
x4 = 7.00000
x5 = 7.00000
x6 = 7.00000


### Problem 3(c):

In [43]:
def f(x):
    return np.pi - 20.0 * np.arctan(1.0 / x) - 8.0 * np.arctan(3.0 / 79.0)

def f_prime(x):
    return 20.0 / (x * x + 1.0)

def newton(x0, max_iter_num = 6):
    res = []
    x = x0
    for _ in range(max_iter_num):
        x = x - f(x) / f_prime(x)
        res.append(x)
    return res

x0 = 5.0
res = newton(x0)

print("Newton's Method:")
for k, x in enumerate(res, start = 1):
    print(f"x{k} = {x:.5f}")

Newton's Method:
x1 = 6.44296
x2 = 6.95661
x3 = 6.99974
x4 = 7.00000
x5 = 7.00000
x6 = 7.00000


### Problem 5(a):

In [44]:
import numpy as np

def lu(A: np.ndarray):
    """
    I am doing the LU decomposition without permutation matrix. I am doing it in the order of calculating the j-th row of U first, then the j-th column of L. The values inside the entries are calculated based on the formula provided in the question description. L is initialized to identity matrix and U is initialized to zero matrix.
    """
    A = np.array(A)
    n = A.shape[0]

    # initialize L to be identity matrix (unit lower triangular matrix) and U to be zero matrix
    L = np.eye(n)
    U = np.zeros((n, n))

    for j in range(n):
        # calculating j-th row of U, where j <= q
        # Here I am using row index as j and column index as q for U
        for q in range(j, n): 
            temp = 0.0
            
            # calculate the sum temp variable by the fomula of u_{ij} (the second relation provided in the question)
            for k in range(j):
                temp += L[j, k] * U[k, q]
            U[j, q] = A[j, q] - temp

        # Check if U_{j,j} is zero or not to prevent dividing by zero.
        if U[j, j] == 0.0:
            print("Zero u_jj detected during LU decomposition.")

        # calculating j-th column of L, where i > j
        # Here I am using column index as i and column index as j for L
        for i in range(j + 1, n):
            temp = 0.0
            
            # calculate the sum temp variable by the fomula of l_{ij} (the first relation provided in the question)
            for k in range(j):
                temp += L[i, k] * U[k, j]
            L[i, j] = (A[i, j] - temp) / U[j, j]

    return L, U

### Problem 5(b):

In [45]:
np.random.seed(0)
A = np.random.rand(5, 5)

L,U = lu(A)

np.set_printoptions(formatter={'float': '{:0.5f}'.format})
print("A :\n", A)
print("\nL :\n", L)
print("\nU :\n", U)

# print("\n error", np.linalg.norm(A - L @ U))

A :
 [[0.54881 0.71519 0.60276 0.54488 0.42365]
 [0.64589 0.43759 0.89177 0.96366 0.38344]
 [0.79173 0.52889 0.56804 0.92560 0.07104]
 [0.08713 0.02022 0.83262 0.77816 0.87001]
 [0.97862 0.79916 0.46148 0.78053 0.11827]]

L :
 [[1.00000 0.00000 0.00000 0.00000 0.00000]
 [1.17689 1.00000 0.00000 0.00000 0.00000]
 [1.44261 1.24432 1.00000 0.00000 0.00000]
 [0.15876 0.23094 -1.31479 1.00000 0.00000]
 [1.78315 1.17822 1.56727 -0.58891 1.00000]]

U :
 [[0.54881 0.71519 0.60276 0.54488 0.42365]
 [0.00000 -0.40411 0.18239 0.32239 -0.11515]
 [0.00000 0.00000 -0.52846 -0.26162 -0.39684]
 [0.00000 0.00000 0.00000 0.27322 0.30758]
 [0.00000 0.00000 0.00000 0.00000 0.30161]]
